Inteli-College/2025-1A-T12-EC05-G02

docs/docs/Sprint-1/Arquitetura/requisitos.md
Este pull request adiciona os requisitos não funcionais.
Criação dos requisitos não funcionais e uma breve pesquisa envolvendo a norma ISO 25010
Para entender melhor as demandas/desempenhos do projeto e também para fins de artefato.
@...
=> docs: adiciona requisitos não funcionais

src/backend/main.py, src/backend/robot/robot.py, src/backend/user/user.py
Este pull request adiciona a base do backend
=> feat: create backend core

docs/docs/intro.md
Este pull request adiciona a intro da sprint no docusaurus.
A introdução da sprint no docusaurus com o status report
Pedido do Murilo
@LauraRodrigues31
=> docs: adiciona a intro da sprint no docusaurus

docs/docs/Sprint-3/_category_.json, docs/docs/Sprint-3/armazenamento.md, docs/docs/Sprint-3/integracao/Circuito Eletrônico.md, docs/docs/Sprint-3/referencias.md, src/frontend/pharmabot/src/app/historico-logs/page.tsx
Este pull request adiciona a documentação do armazenamento de logs.
[Forneça uma descrição detalhada da mudança, por exemplo: criação/atualização de persona, nova funcionalidade, correções, melhorias, etc.]
Conformidade com o artefato
Artefato diz: "- Armazenamento de dados das requisições e outras informações relevantes para o sistema (log) (até 2.0 pontos)." e "Por fim, espera-se ver uma evolução no armazenamento das informações e requisições realizadas para o robô nesta fase do projeto. O formato como os dados serão armazenados, estruturado em tabelas ou semi-estruturado, fica por conta da escolha que o grupo achar mais pertinente, desde que esteja …
=> Documentação do armazenamento de logs

docs/docs/Sprint-3/Backend/robotBack.md
Este pull request adiciona a doc do backend do robo
@matheusjorgerosa
=> doc: backend robot

docs/docs/Sprint-3/integracao/API.md, docs/docs/Tutoriais/API.md, docs/docs/Tutoriais/_category_.json, docs/docs/Tutoriais/intro.md, docs/docs/Tutoriais/rotas.md, docs/docs/intro.md
Este pull request adiciona/atualiza **[descrição sucinta do que está sendo entregue]**.
[Forneça uma descrição detalhada da mudança, por exemplo: criação/atualização de persona, nova funcionalidade, correções, melhorias, etc.]
[Explique a motivação por trás da alteração: quais problemas são resolvidos ou quais benefícios são trazidos.]
@...
=> Documentação - Tutoriais de desenvolvimento e testes

docs/docs/Sprint-3/integracao/sensors.md
Este pull request adiciona a seção de integração dos sensores no código.
O PR adiciona a seção de explicação das funções criadas para integrar a leitura dos sensores no código, além de destacar as mudanças realizadas no código já existente para esta implementação.
=> doc: adiciona seção de integração dos sensores

src/frontend/pharmabot/src/app/components/SelectButton.tsx, src/frontend/pharmabot/src/app/components/Sidebar.tsx, src/frontend/pharmabot/src/app/historico-logs/page.tsx
Codigo de react do component sidebar deslizando da esquerda para a direita com a lista de páginas linkadas com rotas para navegação do usuário. 
´´e importante fazer componentes para melhor fatoração e codificação das telas do sistema
@...
=> feat: add component SideBar

src/frontend/pharmabot/src/app/(auth)/login.module.css, src/frontend/pharmabot/src/app/globals.css, src/frontend/pharmabot/src/app/layout.tsx
Este pull request adiciona **poppins como fonte global**.
adiciona **poppins como fonte global**.
Requisito do figma
@iisabelledantas
=> fix: adiciona poppins como fonte global

src/frontend/pharmabot/src/app/components/TabelaPharma.tsx, src/frontend/pharmabot/src/app/components/table.tsx, src/frontend/pharmabot/src/app/historico-logs/page.tsx
Este pull request permite  **configurar as colunas da tabela**.
Agora dá para definir as colunas da tabela
Tinha me esquecido dessa feature do component
@...
=> fix: permite configurar as colunas da tabela

src/frontend/pharmabot/src/app/historico-logs/page.tsx
Este pull request atualiza **o front da tela de logs**.
- Lógica de exportar dentro de utils
- Estilização dentro de theme.ds.ts
- Filtro dentro de SelectButton.tsx
Toda lógica estava em um component
@julia-lika
=> refactor: refatora a tela historico de logs

src/frontend/pharmabot/src/app/components/FormModal.tsx, src/frontend/pharmabot/src/app/estoque/FormRegistro.tsx, src/frontend/pharmabot/src/app/historico-logs/page.tsx
Este pull request adiciona **o componente de formModal**.
Permite configurar os inputs de um modal
Precisei usar em multiplas telas
@matheusjorgerosa
=> feat: adiciona o componente de formModal

src/frontend/pharmabot/src/app/components/FormModal.tsx, src/frontend/pharmabot/src/app/components/TabelaPharma.tsx, src/frontend/pharmabot/src/app/components/table.tsx, src/frontend/pharmabot/src/app/estoque/FormEditar.tsx, src/frontend/pharmabot/src/app/estoque/page.tsx
Este pull request adiciona **o botão editar com o novo modal FormModal**.
Adiciona botão de editar
Requerimento do grupo
Usar esse código acima do return de page.tsx de estoque: 
```
const data = new Date()
const rowsMock: Data[] = [
{item: 'Omeprazol', codigoIdentificacao: 'A2310A', localizacao: 'A32', quantidade: 3, ultimaAtualizacao: data, id: '4' }
]
```
Para testar
@
=> feat: adiciona o botão de editar

src/backend/main.py, src/backend/storage/storage.py, src/frontend/pharmabot/src/app/estoque/FormRegistro.tsx, src/frontend/pharmabot/src/app/estoque/page.tsx
=> feat: reestrutura requisicao POST do cadastro de item no estoque

src/robot/qrcode_function.py
Este pull request adiciona/atualiza as funções de busca e leitura do qr code
Apenas implementei uma lógica diferente, para que o robô procure pelo qr code durante dois minutos, e caso encontre, pegue o medicamento, caso não, ele apenas passa para o próximo
Pois, anteriormente, o robô busca pelo qr code para sempre, travando a linha de separação de kits
@...
=> feat: limitação de tempo na busca pelo qr code

src/backend/medicine/medicine.py, src/frontend/pharmabot/src/app/components/Sidebar.tsx, src/frontend/pharmabot/src/app/components/home/sidebar-actions.tsx, src/frontend/pharmabot/src/app/estoque/page.tsx, src/frontend/pharmabot/src/app/historico-logs/page.tsx, src/frontend/pharmabot/src/app/home/page.tsx
=> fix: tabela home, caminhos e itens da sidebar

docs/docs/Sprint-4/server.md
Este pull request adiciona a documentação do servidor
@matheusjorgerosa @Lucas-nepomuceno @Gustavo-daCosta
=> doc: server

src/backend/medicine/medicine.py, src/frontend/pharmabot/src/app/components/FormModal.tsx, src/frontend/pharmabot/src/app/estoque/FormRegistro.tsx
Este pull request adiciona a possibilidade de escolher o remédio no registro
Modo antigo não funcionava
@julia-lika
=> feat: permite selecionar o nome do remédio no registro

src/backend/medicine/medicine.py
Este pull request adiciona/atualiza **[descrição sucinta do que está sendo entregue]**.
[Forneça uma descrição detalhada da mudança, por exemplo: criação/atualização de persona, nova funcionalidade, correções, melhorias, etc.]
[Explique a motivação por trás da alteração: quais problemas são resolvidos ou quais benefícios são trazidos.]
@...
=> feat: rota de criar medicamento

docs/docs/Sprint-5/recapitulacao.md, docs/docs/Sprint-5/referencias.md, src/frontend/pharmabot/.env
Este pull request atualiza **os requisitos funcionais e não funcionais**.
Novo arquivo md na sprint 5 com atualizações nos requisitos funcionais e não funcionais
Requerimento do artefato 
O Heitor ainda precisa adicionar a parte dele
@HeitorCand
=> docs: adiciona a recapitulacao dos requisitos na documentacao

docs/docs/Sprint-5/analise-financeira/_category_.json, docs/docs/Sprint-5/analise-financeira/analise-futura.md, docs/docs/Sprint-5/referencias.md
Este pull request adiciona **a análise financeira futura**.
Pesquisa e documentação da analise financeira futura
Requerimento do artefato
@FelipeSimao9
=> docs: adiciona a analise financeira futura
